### ISSUE TITLE
splunk sdk update

### ISSUE THREAD

**Issue by inidona** [commontime/com.commontime.cordova.splunk-mint#1]
Hi, i have forked your repository and updated the sdk to the current version.

are you still maintain this plugin ?
should i create a PR ?

thanks
andreas

**Comment by RevillWeb** [comment]
Hi Inidona, we are no longer using or maintaining this plugin so no need for a PR. Hope it has some use for you, all the best.

**Comment by dilipsarkar** [comment]
Hi Inidona,

Would you be able to share updated version of the plugin? We are planning to use the same for our app.

Thanks,
Dilip

**Comment by dilipsarkar** [comment]
Got it from here https://github.com/inidona/com.commontime.cordova.splunk-mint

Thanks
